# Generated by Django 5.2.3 on 2025-08-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
